apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-service
  labels:
    app: food-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-service
  template:
    metadata:
      labels:
        app: food-service
    spec:
      containers:
      - name: food-service
        image: localhost:5000/food-service:latest
        command: ["/bin/sh", "-c", "rm -f .env && node server.js"]
        ports:
        - containerPort: 4001
        env:
        - name: PORT
          value: "4001"
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: tomato-secrets
              key: MONGO_URL_FOOD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: tomato-secrets
              key: JWT_SECRET
        volumeMounts:
        - name: food-uploads
          mountPath: /app/uploads
      volumes:
      - name: food-uploads
        persistentVolumeClaim:
          claimName: food-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: food-service
spec:
  selector:
    app: food-service
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: food-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
